### ISSUE TITLE
Provide "clarity" mode

### ISSUE THREAD

**Issue by shortjared** [trek10inc/serverless-graph#6]
Many of the nodes in the default graph do nothing but reduce overall clarity and clutter things. We should hide / passthrough dependencies on certain kinds of relationships.

A starting list:

**HIDE**
- Lambda Versions
- Deployment
- Deployment Bucket

**Pass-Through**
- *LambdaPermissionAPIGateway (I could argue we could just hide this Dep all together, it's the connection to `APIGatewayMethods` that matters more here.
- ApiGatewayResourceAdd

Example Before / After on Default SLS Project

### Before

![example](https://user-images.githubusercontent.com/1689118/27048662-afeb4670-4f7a-11e7-8ef2-b7e23445c4df.png)

### After

![example-fixed](https://user-images.githubusercontent.com/1689118/27048666-b34e747c-4f7a-11e7-90e9-315a82c5cb67.png)

**Comment by hauboldj** [comment]
I think we could keep the ApiGatewayResources but drop the restApiId edge from resource to rest api (except for the top level resources)

**Comment by shortjared** [comment]
Moved to https://github.com/trek10inc/cloudformation-graph/issues/3
