### ISSUE TITLE
Split to cloudformation-graph and serverless-graph

### ISSUE THREAD

**Issue by shortjared** [trek10inc/serverless-graph#9]
This shouldn't only be usable by serverless. At the end of the day it's all CFN. Let's solid out the core graph engine and serverless specific stuff before it is too late.

**Comment by hauboldj** [comment]
@shortjared Should we split this into two repositories or keep it in one?

**Comment by shortjared** [comment]
two

**Comment by shortjared** [comment]
In progress: https://github.com/trek10inc/cloudformation-graph
